steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-k8s-429121/container2', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-k8s-429121/container2']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/container2-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=primary'
images:
  - 'gcr.io/cloud-k8s-429121/container2'
