# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: gcr.io/cloud-k8s-429121/container2
          ports:
            - containerPort: 7000
          volumeMounts:
            - mountPath: /arta_PV_dir
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: arta-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
  selector:
    app: container2
